
s: sdasdasd




spring:
  redis:
    database: 0
    host: 192.168.200.130
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 32
        max-wait: -1
        max-idle: 16
        min-idle: 8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    password: 1234
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    addresses: 192.168.200.130
    port: 5973
    username: guest
    password: guest

web:
  redis:
    cluster:
      nodes: 192.168.200.130
      pool:
        max-active: 32
        max-wait: -1
        max-idle: 16
        min-idle: 8

task:
  pool:
    corePoolSize: 5
    maxPoolSize: 5
    keepAliveSeconds: 300
    queueCapacity: 1000

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.demoasdasdqw.pojo
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  auto-dialect: true
  reasonable: true


