spring:
  redis:
    database: 0
    host: 192.168.200.130
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 32
        max-wait: -1
        max-idle: 16
        min-idle: 8